DEEPDIVE-coding-potatoes/Algorithm

최가은/프로그래머스_알고리즘 고득점Kit_스택큐_같은 숫자는 싫어.py
최가은/프로그래머스_알고리즘 고득점Kit_스택큐_기능개발.py

> 20250304
> 프로그래머스 알고리즘 고득점 Kit의 스택/큐 세션 진행중입니다.
`같은 숫자는 싫어` 문제의 경우 배열의 가장 마지막 원소에 접근하는 문제인데, 빈 배열에 접근을 하게되면 에러가 발생합니다.
이 때, `answer[-1:] == [i]`와 같이 빈 배열이 나와도 `[i]`로 배열과 배열을 비교하게 하면 에러가 발생하지 않게 됩니다.
`기능 개발` 문제의 경우 생산하는데 소요되는 시간을 미리 계산하여 `days`에 저장하고, `pivot(front)`을 이용해 값을 비교해서 개수를 세어줬습니다.
>  x

Test: 프로그래머스 알고리즘 고득점Kit Stack | Lv1, 2

---

김소연/문자열붙여서출력.js

> 20250304
> 코딩테스트 기초 학습하였습니다.
>
> 배열길이에따라다른연산.js 파일에서 한줄로 저렇게 쓰는 게 좋은 방식인가요?
체점하고 나서 다른사람풀이를 보면 저렇게 한 줄로 쓰는 사람들이 많길래 저도 해봤는데,,, 제가 볼 때는 가독성이 별로인 것 같아서 의견 여쭤봅니다!

test : 2025-03-04

---

권수영/training_01.js
권수영/training_02.js
권수영/training_03.js
권수영/training_04.js
권수영/training_05.js
권수영/training_06.js
권수영/training_07.js

> 20250304
> 코딩 기초 트레이닝을 정답률 높은 문제부터 풀어나갔습니다.
1. 문자열 붙여서 출력하기
2. 공배수
3. 문자열 정수로 변환하기
4. 홀짝 구분하기
5. 정수부분
6. n의 배수
7. 문자열 출력하기
> 더 좋은 풀이 방법 있다면 적극 환영입니다 👍

Test: 20250304 팀 스터디

---

조연경/프로그래머스_코딩 기초 트레이닝_a와b 출력하기.js
조연경/프로그래머스_코딩 기초 트레이닝_대소문자 바꿔서 출력하기.js
조연경/프로그래머스_코딩 기초 트레이닝_덧셈식 출력.js
조연경/프로그래머스_코딩 기초 트레이닝_문자열 반복해서 출력하기.js
조연경/프로그래머스_코딩 기초 트레이닝_문자열 붙여서 출력.js
조연경/프로그래머스_코딩 기초 트레이닝_문자열 출력하기.js
조연경/프로그래머스_코딩 기초 트레이닝_특수문자출력.js

> 20250304
> 이번 PR에서 작업한 내용(코딩 내용)을 간략히 설명해주세요(이미지 첨부 가능)
문제 푸는거에 초점을 맞춰서 생각나는데로 풀었는데 다음번엔 좀 더 정리해서 풀어야할듯,,😱

Test : 250304_프로그래머스_코딩 기초 트레이닝

---

.gitignore
package-lock.json
package.json
신유승/181946.js
신유승/181947.js
신유승/181948.js
신유승/181949.js
신유승/181950.js
신유승/181951.js
신유승/181952.js

> 2025.03.04
> JavaScript로 문제를 풀어보기 위한 기초를 다지며 아주 기초적인 문제들을 풀어봤습니다.
1. 문자열 출력하기
2. 문자열 반복해서 출력하기
3. 대소문자 바꿔서 출력하기
4. 특수문자 출력하기
5. 덧셈식 출력하기
6. 문자열 붙여서 출력하기
7. a와 b 출력하기
> 바로 React 공부부터 시작을 했기에 콘솔로 출력하는 JavaScript는 어설픈 감이 있습니다. 부족해보이는 부분 보이시면 바로 지적해주시길 바랍니다!

Test: 250304 알고리즘 풀이

---

신유승/181935.js
신유승/181936.js
신유승/181937.js
신유승/181938.js
신유승/181939.js
신유승/181940.js
신유승/181941.js
신유승/181942.js
신유승/181943.js
신유승/181944.js
신유승/181945.js

> 20250305
> 다음 문제를 풀었습니다.
1. 문자열 돌리기
2. 홀짝 구분하기
3. 문자열 겹쳐쓰기
4. 문자열 섞기
5. 문자 리스트를 문자열로 변환하기
6. 문자열 곱하기
7. 더 크게 합치기
8. 두 수의 연산값 비교하기
9. n의 배수
10. 공배수
11. 홀짝에 따라 다른 값 반환하기
문자열 겹쳐쓰기(181943) 부분에서 주어진 문자열 중간에 접근하는 방법을 몰라 찾아보고 풀었습니다.
주어진 문자열을 k번 반복하는 문제였는데, for문을 쓰려다 더 좋은 방법이 없을까 하며 찾아본 코드입니다.
형변환과 관련하여 찾아보게 된 문제(두 수의 연산값 비교하기(181939))입니다.
> 조금 더 신경쓰면 좋겠다고 생각하는 부분이 있으시면 말씀해주십셔!!!

Test: 2025-03-05 신유승 문제 풀이

---

권수영/training_08.js
권수영/training_09.js
권수영/training_10.js
권수영/training_11.js
권수영/training_12.js
권수영/training_13.js
권수영/training_14.js
권수영/training_15.js

> 20250305
> 1. a와 b 출력하기
처음에는 +를 사용해 문자열을 연결하였는데 ,도 사용하여 코드를 조금 수정하였다.
> 2. 문자열 반복해서 출력하기
repeat(count) 메서드 사용
repeat 메서드는 문자열을 count만큼 반복해 붙인 새 문자열을 반환한다.
> 3. 대소문자 바꿔서 출력하기
변환 값 저장할 answer 문자열 변수 준비
for문을 사용해 str 만큼 반복
i가 대문자라면 소문자로 변환 후 answer 문자열 변수에 저장
그게 아니라면 대문자로 변환 후 answer 문자열 변수에 저장
answer 문자열 변수 출력
toUpperCase() : 대문자로 변환
toLowerCase() : 소문자로 변환
> 4. 특수문자 출력하기
\ 가 표시되려면 연속으로 써야함
직접 표기되려면 백틱을 사용
> 5. 덧셈식 출력하기
'+' 를 사용하면 문자열을 연결해 출력할 수 있다.
',' 도 사용할 수 있었는데 깜빡 했네,,
> 6. 문자열 돌리기
for문을 사용해 한글자씩 출력
> 7. 문자열 겹쳐쓰기
my_string을 문자의 배열로 변환 후 인덱스 s에서부터 시작하는 문자열을 overwrite_string.length에 해당하는 만큼 overwrite_string으로 대체
수정된 배열을 문자열로 결합 후 반환
splice(start, deleteCount, newItem, newItem, …) 메소드 사용
splice 메서드는 요소를 삭제함과 동시에 새 요소를 추가할 수 있다.
> 8. 배열의 길이에 따라 다른 연산하기
if문을 사용해 배열 길이 홀짝 판별
map() 메서드를 사용해 …

Test: 250305 코딩 기초 문제풀이

---

김소연/A강조하기.js
김소연/rny_string.js
김소연/공배수.js
김소연/공백으로구분하기.js
김소연/뒤에서5등까지.js
김소연/문자열바꿔서찾기.js
김소연/문자열붙여서출력.js
김소연/문자열을정수로변환.js
김소연/배열비교하기.js
김소연/배열의길이에따른다른연산.js
김소연/배열의원소만큼추가.js
김소연/원소들의곱과합.js
김소연/정수부분.js
김소연/특정한문자를대문자로.js
김소연/홀짝구분하기.js

>2025-03-05
> 오늘 문제가 map과 join을 많이 사용하는 문제여서 검색해 가며 풀어보았습니다!
>소문자로 먼저바꿔놓지 않고, 'a' 또는 'A' 이면 대문자로, 아니면 소문자로 바꾸라고 해보고 싶은데 어렵네요..
혹시 힌트가 있다면 알려주시면 감사하겠습니다!

Test :(김소연) 2025-03-05 코딩테스트 문제풀이

---

김소연/test1.js
김소연/test2.js
김소연/test3.js
김소연/test4.js
김소연/test5.js
김소연/test6.js
김소연/test7.js
김소연/test8.js

> 2025-03-06
1. map 
- 배열을 순회하며 원하는 값을 배열로 반환한다.
- 조건에 맞는 값만 반환하고 싶다면 새로 배열을 만들거나, filter함수를 사용 할 것
2. filter
- 배열을 반환하며 조건에 맞는 값을 배열로 반환한다.
3. reduce
- 배열을 돌며 누산한다.
- array.reduce( (누산값 , 현재값, 현재 인덱스, 원본배열) => { 연산 } , 첫번째값 )
첫번째 값은 연산을 시작할 값을 의미한다. 기본으로 0 이 설정되어 있고, 0 또는 1을 설정할 수 있다. 
>
> ex. 이런 문제를 풀 때 어떤 메서드를 사용하면 좋을까요?

Test : 2025-03-06 코딩테스트

---

김소연/test10.js
김소연/test11.js
김소연/test12.js
김소연/test13.js
김소연/test14.js
김소연/test15.js
김소연/test16.js
김소연/test17.js
김소연/test9.js

>20250310
> Index 찾기
- 배열에서 찾은 첫번째 요소가 필요한 경우 find()
- 배열에서 찾은 요소의 인덱스가 필요한 경우 findIndex()
- 값의 인덱스를 찾아야 하는 경우 indexOf()
1. find() 
- 조건에 맞는 첫 번째 요소 반환
- 조건에 맞는 요소가 없다면 undefined 반환
2. findIndex 
- 조건에 맞는 첫 번째 요소의 인덱스 반환
- 조건메 맞는 요소가 없다면 -1 반환
3. indexOf(찾을 요소, 시작할 인덱스)
- 시작할 인덱스는 생략 가능, 생략한다면 처음부터 찾는다.
- 찾는 요소가 있다면 가장 첫번째 요소의 인덱스를 반환한다.
- 찾는 요소가 없다면 -1을 반환한다.
for문에서 배수만큼 커지게 하고 싶을 땐 'i += 배수' 를 써주는 방법이 있다.
>
> ex. 이런 문제를 풀 때 어떤 메서드를 사용하면 좋을까요?

Test : 2025-03-10코딩테스트

---

권수영/training_33.js
권수영/training_34.js
권수영/training_35.js
권수영/training_36.js
권수영/training_37.js
권수영/training_38.js
권수영/training_39.js
권수영/training_40.js
권수영/training_41.js

> 20250311
> 코딩 기초 트레이닝 문제 9문제 풀이
1. 수열과 구간 쿼리 2
2. 수열과 구간 쿼리 4
처음에 i가 arr[i]를 의미하는 줄 알았으나,
[0,4,1] -> 0 <= i <= 4일 때 i가 k의 배수라는 뜻..
3. 배열 만들기 2
4. 카운트 업
5. 콜라츠 수열 만들기
6. 배열 만들기 4
7. 간단한 논리 연산
8. 주사위 게임 3
9. 글자 이어 붙여 문자열 만들기
8. 주사위 게임 3의 다른 풀이
다른 풀이를 보니 내 코드보다 더 단순한 코드가 있었다..
>
> 보다 좋은 풀이가 있다면 알려주세요! 👍

Test: 2025-03-11 코딩 기초 트레이닝 문제 풀이

---

신유승/181901.js
신유승/181902.js
신유승/181903.js
신유승/181904.js
신유승/181905.js
신유승/181906.js
신유승/181907.js
신유승/181908.js
신유승/181909.js
신유승/181910.js

> 20250312
다음 문제를 풀었습니다.
1. 접미사 배열
2. 접미사인지 확인하기
3. 문자열 뒤의 n 글자
4. 문자열 앞의 n 글자
5. 접두사인지 확인하기
6. 문자열 뒤집기
7. 세로 읽기
8. qr code
9. 문자 개수 세기
10. 배열 만들기 1
Ascii 코드가 익숙하다 보니 문자 개수 세기를 Ascii코드를 사용하여 풀어봤습니다. c언어와 js의 정수형, 문자형 처리 방식이 달라 조금 헤맸습니다. 
접미사인지 확인하기 위한 문제인데, 문자열 쪼개고 인덱스로 자르고, 생각하며 풀어봤지만 endsWith라는 아주 좋은 풀이 방식에 벙쪘습니다. (접두사는 startsWith)
문제 풀이 지적, 질문 환영입니다.

Test: 신유승 2025-03-12 알고리즘 풀이

---

조연경/프로그래머스_코딩 기초 트레이닝_문자열 뒤의 n글자.js
조연경/프로그래머스_코딩 기초 트레이닝_문자열 뒤집기.js
조연경/프로그래머스_코딩 기초 트레이닝_문자열 앞의 n글지.js
조연경/프로그래머스_코딩 기초 트레이닝_부분문자열 이어붙여 문자열 만들기.js
조연경/프로그래머스_코딩 기초 트레이닝_접두사인지 확인하기.js
조연경/프로그래머스_코딩 기초 트레이닝_접미사 배열.js
조연경/프로그래머스_코딩 기초 트레이닝_접미사인지 확인하기.js

> 250312
> 이번 PR에서 작업한 내용(코딩 내용)을 간략히 설명해주세요(이미지 첨부 가능)
> 1. 부분 문자열 이어 붙여 문자열 만들기
> 2. 문자열 뒤의 n글자
> 3. 접미사 배열
> 4. 접미사인지 확인하기
> 5. 문자열 앞의 n글자
> 6. 접두사인지 확인하기
> 7. 문자열 뒤집기
> 문제 수가 줄어 든 대신, 풀이 시 사용했던 메서드, 알게된 메서드 등을 주석으로 정리했습니다.
> 코테 풀이시 알게된 내용, 헷갈렸던 부분에 대한 첨언 및 다른 풀이에 관한 내용은 코드 안에 주석으로 남겨뒀으니 참고 부탁드립니다!! :)

Test: 25-03-12 조연경 알고리즘 문제풀이

---

권수영/training_42.js
권수영/training_43.js
권수영/training_44.js
권수영/training_45.js
권수영/training_46.js
권수영/training_47.js
권수영/training_48.js
권수영/training_49.js
권수영/training_50.js

> 20250312
> 코딩 기초 트레이닝 9문제 풀었습니다
- slice() : start ~ end (end 제외) 요소 복사
- reverse() : 배열을 역순으로 정렬
- sort() : 배열의 요소를 문자열로 변환하여 정렬. 숫자 배열을 정렬할 때는 꼭 비교 함수를 작성해야 한다.
- endsWith() : 문자열이 특정 문자열로 끝나는지 확인하고 true / false 로 반환
- startsWith() : 문자열이 특정 문자열로 시작하는지 확인하고 true / false 로 반환
> 
> 더 좋은 풀이가 있다면 알려주세요! 👍

Test: 2025-03-12 코딩 기초 트레이닝 문제 풀이

---

신유승/181892.js
신유승/181893.Js
신유승/181894.js
신유승/181895.js
신유승/181896.js
신유승/181897.js
신유승/181898.js
신유승/181899.js
신유승/181900.js

> 20250313
다음 문제를 풀었습니다.
1. 글자 지우기
2. 카운트 다운
3. 가까운 1 찾기
4. 리스트 자르기
5. 첫 번째로 나오는 음수
6. 배열 만들기 3
7. 2의 영역
8. 배열 조각하기
9. n번째 원소부터
10. 순서 바꾸기
indexOf는 알고 있었지만 lastIndexOf에 대해서 알아가게 된 문제입니다.
가까운 1 찾기, 리스트 자르기, 배열 조각하기 문제는 가장 최근 커밋을 확인해주시면 되겠슴미다.
문제풀이 지적, 질문 환영입니다.

Test: 2025-03-13 신유승 알고리즘 풀이

---

김소연/0떼기.js
김소연/9로나눈나머지.js
김소연/x사이의개수.js
김소연/공백으로구분하기1.js
김소연/꼬리문자열.js
김소연/배열의원소삭제.js
김소연/부분문자열.js
김소연/부분문자열인지확인.js
김소연/정수찾기.js
김소연/특별한이차원배열2.js

> 20250313
> 1. 9로 나눈 나머지
자바스크립트에서 Number타입은 표현할 수 있는 최대 정수 값이 제한적이다.(16자리)
따라서 그냥 숫자로 변환하면 정확한 계산이 되지 않으므로 split을 통해 한자리씩 쪼개야 한다.
> 2. 정규 표현식 뿌시기
https://velog.io/@purplew/Javascript-%EC%A0%95%EA%B7%9C%ED%91%9C%ED%98%84%EC%8B%9D
블로그를 보면서 코드를 작성했다.
>
>

Test : 2025-03-13 코딩테스트

---

조연경/프로그래머스_코딩 기초 트레이닝_qr code.js
조연경/프로그래머스_코딩 기초 트레이닝_가까운 1 찾기.js
조연경/프로그래머스_코딩 기초 트레이닝_글자 지우기.js
조연경/프로그래머스_코딩 기초 트레이닝_리스트 자르기.js
조연경/프로그래머스_코딩 기초 트레이닝_문자 개수 세기.js
조연경/프로그래머스_코딩 기초 트레이닝_배열만들기1.js
조연경/프로그래머스_코딩 기초 트레이닝_세로 읽기.js
조연경/프로그래머스_코딩 기초 트레이닝_첫번째로 나오는 음수.js
조연경/프로그래머스_코딩 기초 트레이닝_카운트 다운.js

> 20250313
> 1. 세로 읽기
> 2. qr code
> 3. 문자 개수 세기
> 4. 배열 만들기 1
> 5. 글자 지우기
> 6. 카운트 다운
> 7. 가까운 1 찾기
> 8. 리스트 자르기
> 9. 첫 번째로 나오는 음수
> 알게된 메서드
> 1. Math.floor(n / k) : n을 k로 나눈 몫을 계산해서 배열 길이 결정
> 2. findIndex() : 배열에서 주어진 조건을 만족하는 첫 번째 요소의 인덱스를 반환
> 코테 풀이시 알게된 내용, 헷갈렸던 부분에 대한 첨언 및 다른 풀이에 관한 내용은 코드 안에 주석으로 남겨뒀으니 참고 부탁드립니다!! :)
> 이번 풀이에는 반복문을 많이 사용했는데, 혹시 더 좋은 풀이가 있다면 코멘트로 남겨주시면 감사하겠습니다👍

Test: 25-03-13 조연경 알고리즘 풀이

---

조연경/프로그래머스_코딩 기초 트레이닝_ n개 간격의 원소들.js
조연경/프로그래머스_코딩 기초 트레이닝_ 순서바꾸기.js
조연경/프로그래머스_코딩 기초 트레이닝_2의영역.js
조연경/프로그래머스_코딩 기초 트레이닝_5명씩.js
조연경/프로그래머스_코딩 기초 트레이닝_n번째 원소까지.js
조연경/프로그래머스_코딩 기초 트레이닝_n번째 원소부터.js
조연경/프로그래머스_코딩 기초 트레이닝_배열만들기3.js
조연경/프로그래머스_코딩 기초 트레이닝_홀수vs짝수.js
조연경/프로그래머스_코딩 기초_배열 조각하기.js
조연경/프로그래머스_코딩 기초_왼쪽오른쪽.js

> 20250317
> 1. 배열 만들기3
> 2. 2의 영역
> 3. 배열 조각하기
> 4. n번째 원소부터
> 5. 순서바꾸기
> 6. 왼쪽 오른쪽
> 7. n번째 원소까지
> 8. n개 간격의 원소들
> 9. 홀수vs짝수
> 10. 5명씩
> 이번 풀이는 조금 수월했던것 같습니다!
> 코테 풀이시 알게된 내용, 헷갈렸던 부분에 대한 첨언 및 다른 풀이에 관한 내용은 코드 안에 주석으로 남겨뒀으니 참고 부탁드립니다!! :)
> 더 좋은 풀이가 있다면 언제든지 코멘트로 남겨주시면 감사하겠습니다👍

Test: 25-03-17 조연경 알고리즘 문제풀이

---

권수영/0317/181889_n 번째 원소까지.js
권수영/0317/181890_왼쪽 오른쪽.js
권수영/0317/181891_ 순서 바꾸기.js
권수영/0317/181892_n 번째 원소부터.js
권수영/0317/181893_배열 조각하기.js
권수영/0317/181894_2의 영역.js
권수영/0317/181895_배열 만들기 3.js
권수영/0317/181896_첫 번째로 나오는 음수.js
권수영/0317/181897_리스트 자르기.js

> 20250317
> 코딩 기초 트레이닝 9문제 풀었습니다
- findIndex 함수 : 만족하는 인덱스를 리턴하고 없으면 자동으로 -1 리턴
- indexOf 함수 : 특정 요소가 처음으로 나타나는 인덱스를 리턴, 없으면  -1 리턴
- lastIndexOf 함수 : 특정 요소가 마지막으로 나타나는 인덱스를 리턴, 없으면 -1 리턴
1. 리스트 자르기
다른 풀이를 참고하니 case 4 부분을 filter 함수를 사용해 간단히 나타낼 수 있었다.
```javascript
return num_list.slice(a, b + 1).filter((_, idx) => !(idx % c));
``` 
2. 첫 번째로 나오는 음수
처음에 forEach 문을 사용할 수 있을 줄 알았으나, forEach 함수는 순회 도중 리턴이 불가능 하다는 걸 깨달음
제출 후 다른 풀이를 보고 findIndex 함수로 간단히 구현 가능하다는 걸 알게 되었다.
3. 배열 만들기 3
4. 2의 영역
5. 배열 조각하기
여러 방법을 활용한 풀이들이 많았다. map, slice, reduce, filter…
6. n 번째 원소부터
7. 순서 바꾸기
8. 왼쪽 오른쪽
9. n 번째 원소까지
>
> 더 좋은 풀이가 있다면 알려주세요! 👍

Test: 2025-03-17 코딩 기초 트레이닝 9문제

---

신유승/181871.js
신유승/181872.js
신유승/181873.js
신유승/181874.js
신유승/181875.js
신유승/181876.js
신유승/181877.js
신유승/181878.js
신유승/181879.js
신유승/181880.js

> 20250318
다음 문제를 풀었습니다.
1. 1로 만들기
2. 길이에 따른 연산
3. 원하는 문자열 찾기
4. 대문자로 바꾸기
5. 소문자로 바꾸기
6. 배열에서 문자열 대소문자 변환하기
7. A 강조하기
8. 특정한 문자를 대문자로 바꾸기
9. 특정 문자열로 끝나는 가장 긴 부분 문자열 찾기
10. 문자열이 몇 번 등장하는지 세기
위 문제를 풀면서 indexOf의 사용법을 확장하였고, 정규 표현식에 대한 풀이도 알아가게 되었습니다.
지적, 질문 언제나 환영입니다.

Test: 신유승 2025-03-18 알고리즘 풀이

---

김소연/문자열출력하기.js
김소연/배열만들기2.js
김소연/배열조각하기.js
김소연/전국대회선발고사.js
김소연/정사각형으로만들기.js
김소연/코드처리하기.js

> 20250317
> 정규식으로도 될 것 같은데,,, 시간이 없어서 조금 더 생각해 봐야 할 것 같네용..ㅠ
>
>

Test : 2025-03-19 코딩테스트

---

신유승/181830.js
신유승/181836.js
신유승/181837.js
신유승/181846.js
신유승/181851.js
신유승/181855.js
신유승/181857.js
신유승/181858.js
신유승/181859.js
신유승/181862.js

> 20250319
다음 문제를 풀었습니다.
1. 전국 대회 선발 고사
2. 정사각형으로 만들기
3. 그림 확대
4. 무작위로 K개의 수 뽑기
5. 두 수의 합
6. 배열 만들기 6
7. 커피 심부름
8. 문자열 묶기
9. 세 개의 구분자
10. 배열의 길이를 2의 거듭제곱으로 만들기
확인하려는 수가 2의 제곱수인지 확인하기 위한 코드를 찾아봤습니다. 위 반복문은 2진수를 사용한 것입니다.
질문, 지적 언제나 환영입니다.

Test: 신유승 2025-03-19 알고리즘 풀이

---

권수영/0320/12935_제일 작은 수 제거하기.js
권수영/0320/12940_최대공약수와 최소공배수.js
권수영/0320/12948_핸드폰 번호 가리기.js
권수영/0320/340213_동영상 재생기.js
권수영/0320/68935_3진법 뒤집기.js

> 20250320
> lv 1 정답률 높은 문제 4문제와 낮은 문제 1문제를 풀었습니다.
>
> 쉽게 풀리지 않아서 오래 걸렸네요 ;-; 지적 언제나 환영입니다..

Test: 2025-03-20 코딩 테스트 연습 Lv 1 풀이

---

조연경/프로그래머스_코딩 기초 트레이닝_Lv.1/난이도 상_동영상 재생기.js
조연경/프로그래머스_코딩 기초 트레이닝_Lv.1/난이도 하_3진법 뒤집기.js
조연경/프로그래머스_코딩 기초 트레이닝_Lv.1/난이도 하_제일 작은 수 제거하기 .js
조연경/프로그래머스_코딩 기초 트레이닝_Lv.1/난이도 하_최대공약수와 최소공배수.js
조연경/프로그래머스_코딩 기초 트레이닝_Lv.1/난이도 하_핸드폰 번호 가리기.js

>250320
> 1. 제일 작은 수 제거하기
> 2. 핸드폰 번호 가리기
> 3. 최대공약수와 최소공배수
> 4. 3진법 뒤집기
> 5. 동영상 재생기
> 1~4 번은 수월하게 풀었습니다. 
5번 동영상 재생기 문제는 문제가 어렵다기 보단 조건이 많아서 정리하는데 오래걸린 문제였음
> 주석으로 정리되어 있는 부분은 풀면서 제가 이해하려고 적어둔 부분이니 참고부탁드립니당~!
> 더 나은 풀이나 피드백은 언제나 환영입니다!!

Test: 25-03-20 조연경 Lv.1 알고리즘 풀이

---

신유승/178871.js
신유승/68644.js
신유승/81301.js
신유승/86491.js

250326
다음 문제를 풀었습니다.
1. 최소직사각형
2. 두 개 뽑아서 더하기
3. 숫자 문자열과 영단어
4. 달리기 경주
지적 혹은 질문 언제나 환영입니다.

Test: 20250326 신유승 알고리즘 풀이
